#!/bin/sh

commit_type=""
base_regex="(\w*$commit_type\w*): .+"

line=$(head -n 1 ${1})
count=${#line}
description=$(head -n 1 ${1} | cut -d ":" -f 2)

ret=$(grep -E "$base_regex" ${1})
test -n "$ret" || {
    echo >&2 "ERROR: Commit message don't follow the following format -> <type>: <message>"
	echo >&2 "-> <type> needs to be one of the following -> add, remove, fix, build, docs, feat, refactor, style, test"
    exit 1
}

